version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    reviewers:
      - "jibin7jose"
    assignees:
      - "jibin7jose"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 8
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "deps(npm)"
    groups:
      npm-non-major:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    reviewers:
      - "jibin7jose"
    assignees:
      - "jibin7jose"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps(actions)"
    groups:
      actions-non-major:
        update-types:
          - "minor"
          - "patch"
